name: Build Debug APK

on:
  push:
    branches:
      - main  # Agar tu kisi aur branch pe push karta hai, yaha uska naam daal sakta hai
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: TapnexEmpire-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
